development:
  adapter: postgresql
  encoding: unicode
  database: nyhrc_development
  pool: 5
  username:
  password:
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: nyhrc_test
  pool: 5
  username:
  password:
  host: localhost

